### PR TITLE
readsbrrd: fix compilation with GCC 14

### PR DESCRIPTION
**Pull request by stintel**
Due to stricter defaults in GCC 14, readsb compile fails with the following errors in readsbrrd.c:
```
readsbrrd.c: In function ‘rrd_create_files’:
readsbrrd.c:219:46: error: passing argument 2 of ‘rrd_create’ from incompatible pointer type [-Werror=incompatible-pointer-types]
  219 |         rrd.status = rrd_create(rrd.argc, rrd.argv);
      |                                           ~~~^~~~~
      |                                              |
      |                                              char **
In file included from readsbrrd.h:29,
                 from readsbrrd.c:20:
/usr/include/rrd.h:158:5: note: expected ‘const char **’ but argument is of type ‘char **’
  158 |     const char **);
      |     ^~~~~~~~~~~~~
readsbrrd.c: In function ‘rrd_update_file’:
readsbrrd.c:249:42: error: passing argument 2 of ‘rrd_update’ from incompatible pointer type [-Werror=incompatible-pointer-types]
  249 |     rrd.status = rrd_update(rrd.argc, rrd.argv);
      |                                       ~~~^~~~~
      |                                          |
      |                                          char **
/usr/include/rrd.h:179:5: note: expected ‘const char **’ but argument is of type ‘char **’
  179 |     const char **);
      |     ^~~~~~~~~~~~~
```

### CODE REVIEW

**Comment by Mictronics** [comment]
@stintel Not only a GCC problem. Build fails on my side with librrd-dev v1.7.2-3.
```
readsbrrd.c: In function ‘rrd_create_files’:
readsbrrd.c:219:43: error: passing argument 2 of ‘rrd_create’ from incompatible pointer type [-Werror=incompatible-pointer-types]
  219 |         rrd.status = rrd_create(rrd.argc, (const char **) rrd.argv);
      |                                           ^~~~~~~~~~~~~~~~~~~~~~~~
      |                                           |
      |                                           const char **
In file included from readsbrrd.h:29,
                 from readsbrrd.c:20:
/usr/include/rrd.h:157:5: note: expected ‘char **’ but argument is of type ‘const char **’
  157 |     char **);
      |     ^~~~~~~
readsbrrd.c: In function ‘rrd_update_file’:
readsbrrd.c:249:39: error: passing argument 2 of ‘rrd_update’ from incompatible pointer type [-Werror=incompatible-pointer-types]
  249 |     rrd.status = rrd_update(rrd.argc, (const char **) rrd.argv);
      |                                       ^~~~~~~~~~~~~~~~~~~~~~~~
      |                                       |
      |                                       const char **
In file included from readsbrrd.h:29,
                 from readsbrrd.c:20:
/usr/include/rrd.h:174:5: note: expected ‘char **’ but argument is of type ‘const char **’
  174 |     char **);
      |     ^~~~~~~
```
What is your librrd-dev version? 1.8.0 probably.
librrd-dev doesn't expose its version to the pre-processor.

**Comment by Mictronics** [comment]
@stintel Added a work around to build with librrd-dev v1.7.2 or v1.8.0+. Please check on your build environment.
